version: '3'
services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    expose:
      - "80"  # Expose port 80 internally for other services

  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - NODE_ENV=dev
      - ACCESS_TOKEN_SECRET=
      - REFRESH_TOKEN_SECRET=
    expose:
      - "3000"  # Expose port 3000 internally for other services
    volumes:
      - data:/app/data  # Mount the volume to /app/data in the backend

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"  # Expose the reverse proxy on port 8080
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

volumes:
    data: